# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 061ea770477bc9a2f89a7cbe13213d297936381284d6bd13a4f250ce9a3d12519335a9718410ef846dcd856cc77df3902708102869c9c12bf04b4b2741730439

test:
  secret_key_base: 7d07d8f8fd11a2d7a91516fdf40d1dc13408e6f529ce202e4cb07a9dbd44337d5afcf771fe65f43c06f07a159631959f92cc75b1eee4e0c63d6dc8a16a638918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
